[target.thumbv6m-none-eabi]
runner    = "probe-rs run --chip RP2040 --protocol {{PROTOCOL}}"
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tmemory.x"]

[build]
target = "thumbv6m-none-eabi"
