[target.thumbv7em-none-eabihf]
# teensy_loader_cli expects a .hex; wrap with objcopy
runner    = "sh -c 'arm-none-eabi-objcopy -O ihex $0 $0.hex && teensy_loader_cli --mcu=TEENSY32 -w -v $0.hex'"
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tmemory.x"]

[build]
target = "thumbv7em-none-eabihf"
