[board]
name   = "STM32F103 Blue Pill"
chip   = "STM32F103C8Tx"
target = "thumbv7m-none-eabi"

[probe]
protocol = "Swd"
speed    = 4000

[flash]
restore_unwritten = false
halt_afterwards   = false

[rtt]
enabled  = true
channels = [{ up = 0, name = "Terminal" }]

[new_project]
runner = "probe-rs run --chip STM32F103C8Tx --protocol swd"

dependencies = '''
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
nb = "1.1.0"
panic-halt = "1.0.0"
rtt-target = "0.6.2"
stm32f1xx-hal = { version = "0.11.0", features = ["stm32f103"] }

'''

files = """
rustdyno.toml
src/main.rs
memory.x
.cargo/config.toml
"""

replace = """
rustdyno.toml
memory.x
.cargo/config.toml
"""
