[board]
name   = "nRF52840 DK"
chip   = "nRF52840_xxAA"
target = "thumbv7em-none-eabihf"

[probe]
protocol = "swd"
speed    = 4000          # kHz

[flash]
restore_unwritten = false
halt_afterwards   = false

[rtt]
enabled  = true
channels = [{ up = 0, name = "Terminal" }]

[new_project]
runner = "probe-rs run --chip nRF52840_xxAA --protocol swd"

dependencies = '''
cortex-m         = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt      = "0.7.5"
panic-halt       = "1.0"
rtt-target       = "0.6"
nrf52840-hal     = { version = "0.16", features = ["rt"] }
'''

files = """
rustdyno.toml
src/main.rs
Embed.toml
memory.x
.cargo/config.toml
"""

replace = """
rustdyno.toml
Embed.toml
memory.x
.cargo/config.toml
"""
